In [12]:
print("Hello World")

Hello World


In [13]:
print("Sibasish")

Sibasish


Print("Sibasish")


In [14]:
Print("Sibasish")

NameError: name 'Print' is not defined

### Python is case sensitive

In [5]:
print(10)

10


In [6]:
print(sibasish)

NameError: name 'sibasish' is not defined

#### String should be within inverted comma ("")

### Shortcut Keys

###### Run -> Shift + Enter

##### Add a cell above -> a
##### Add a cell below -> b
##### Delete a cell -> x

In [7]:
x = 10
type(x)

int

In [8]:
x = 11.34
type(x)

float

In [9]:
x = ('Data science')
type(x)

str

#### Variables

In [10]:
coursenames = ("DS", "BA" , "Math")
coursenames

('DS', 'BA', 'Math')

In [11]:
course names = ("DS", "BA" , "Math")
course names

SyntaxError: invalid syntax (2012602144.py, line 1)

##### Space is not allowed
##### The only allowed special character is underscore (_)

##### Variable names should not start with a number

##### Name should start with A-Z, a-z , underscore (_)

### DATA STRUCTURES

In [1]:
sample_list=[1,13.6,"Hi",12,1]
sample_list

[1, 13.6, 'Hi', 12, 1]

In [2]:
sample_list[2]

'Hi'

In [3]:
sample_list[10]

IndexError: list index out of range

In [4]:
sample_list[0]=100
sample_list

[100, 13.6, 'Hi', 12, 1]

#### List uses square brackets
#### Hetrogenous
#### Mutable
#### List can be retrieved using index

#### Tuple

In [5]:
sample_tuple=(1,13.6,"hi",12,1)
sample_tuple

(1, 13.6, 'hi', 12, 1)

In [6]:
sample_tuple(2)

TypeError: 'tuple' object is not callable

In [7]:
sample_tuple[2]

'hi'

In [8]:
sample_tuple[0]=100

TypeError: 'tuple' object does not support item assignment

#### Immutable
#### Tuple can be retrieved using index
#### Heterogeneous
#### Tuple uses Parenthesis

## SET

In [15]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [16]:
sample_set[0]

TypeError: 'set' object is not subscriptable

In [17]:
sample_set[0]="hello"
sample_set

TypeError: 'set' object does not support item assignment

In [18]:
sample_set.add(1000)
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [13]:
sample_set.remove("hi")
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

#### Mutable but using add and subtract
#### Doesn't allow duplicates
#### Ordered first place
#### In set, elements cannot be retrieved using index rather than using add or subtract

## Dictionary

In [15]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:"35.4",7:35.4}
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 35.4}

In [11]:
sample_dict[1]

NameError: name 'sample_dict' is not defined

In [17]:
sample_dict[7]=100
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100}

In [18]:
sample_dict[10]="Business"
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100, 10: 'Business'}

#### Has key-value data structure
#### key can't be retrieved using index
#### key is unique
#### values can be duplicated
#### values can be retrieved using key

### Numpy : Package for Multidimensional Array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_arrays=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_arrays)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(20,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Create an array of zeros with 2 rows and 10 columns

In [19]:
import numpy as np

In [20]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(3,2)

array([[0.5412234 , 0.57501095],
       [0.70892092, 0.74959837],
       [0.04840751, 0.59768054]])

In [25]:
np.random.rand(3,2)

array([[0.99778303, 0.59196436],
       [0.14796812, 0.67782042],
       [0.24751907, 0.95128281]])

In [26]:
np.random.randint(34,100)

35